create extension if not exists pgcrypto;

create table if not exists public.chat_conversations (
  id uuid primary key default gen_random_uuid(),
  public_id uuid not null unique,
  access_token_hash text not null,
  name text not null,
  email text not null,
  status text not null default 'open' check (status in ('open', 'closed')),
  created_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.chat_conversations(id) on delete cascade,
  sender text not null check (sender in ('visitor', 'operator')),
  body text not null check (char_length(body) between 1 and 2000),
  telegram_message_id bigint,
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_conversation_created_idx
  on public.chat_messages (conversation_id, created_at);

create index if not exists chat_messages_telegram_id_idx
  on public.chat_messages (telegram_message_id)
  where telegram_message_id is not null;

alter table public.chat_conversations enable row level security;
alter table public.chat_messages enable row level security;

-- Nessuna policy pubblica: accesso solo dal backend con la service role key.
